import turtle
window = turtle.Screen()
window.setup(width = 600, height=600)

letterHeight = 400
lineWidth = 20
rightWall = 0
leftX = 0
leftY = 0
rightX = 0
rightY = 0

turtle.mode("logo")
turtle.penup()
turtle.pencolor("red")
turtle.goto(-300, -250)
turtle.pendown()
turtle.setheading(90)
turtle.forward(600)
turtle.penup()
turtle.goto(250, -300)
turtle.pendown()
turtle.setheading(0)
turtle.forward(600)
turtle.penup()
turtle.goto(300, 250)
turtle.pendown()
turtle.setheading(270)
turtle.forward(600)
turtle.penup()
turtle.goto(-250, 300)
turtle.pendown()
turtle.setheading(180)
turtle.forward(600)
turtle.penup()
turtle.pencolor("blacK")

turtle.goto(-letterHeight / 2, -lineWidth)
turtle.pendown()


#START
turtle.begin_fill()
turtle.setheading(330)
turtle.forward(lineWidth)
turtle.setheading(90)
turtle.forward(letterHeight / 4)
turtle.setheading(150)
turtle.forward(lineWidth)
turtle.setheading(90)
turtle.forward(letterHeight / 4)
turtle.setheading(330)
turtle.forward(lineWidth / 2)
turtle.setheading(270)
turtle.forward(letterHeight / 4 - lineWidth)
turtle.setheading(330)
turtle.forward(lineWidth)
turtle.setheading(90)
turtle.forward(letterHeight / 4)
ReturnPoint = turtle.position()
turtle.setheading(150)
turtle.forward(lineWidth * 1.5)
turtle.setheading(210)
turtle.forward(lineWidth)
turtle.setheading(270)
turtle.forward(letterHeight / 4 + lineWidth)
turtle.setheading(330)
turtle.forward(lineWidth)
turtle.setheading(270)
turtle.forward(letterHeight / 4 - lineWidth)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint)
turtle.setheading(330)
turtle.forward(lineWidth / 2)
turtle.pendown()
turtle.begin_fill()
ReturnPoint = turtle.position()
turtle.setheading(270)
turtle.forward(letterHeight / 3)
turtle.setheading(210)
turtle.forward(lineWidth / 2)
turtle.setheading(270)
turtle.forward(lineWidth)
turtle.setheading(30)
turtle.forward(lineWidth * 1.5)
turtle.setheading(90)
turtle.forward(letterHeight / 3)
turtle.setheading(30)
turtle.forward(lineWidth)
turtle.setheading(90)
turtle.forward(lineWidth)
turtle.setheading(210)
turtle.forward(lineWidth * 2)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint)
turtle.setheading(90)
turtle.forward(lineWidth / 2)
turtle.pendown()
turtle.begin_fill()
ReturnPoint = turtle.position()
turtle.setheading(30)
turtle.forward(lineWidth * 2)
rightWall = turtle.xcor()
turtle.setheading(150)
turtle.forward(lineWidth)
turtle.setheading(210)
turtle.forward(lineWidth)
turtle.setheading(150)
turtle.forward(lineWidth * 3)
turtle.setheading(210)
turtle.forward(lineWidth)
turtle.setheading(330)
turtle.forward(turtle.distance(ReturnPoint) )
turtle.end_fill()
#END

turtle.done()