import turtle
window = turtle.Screen()
window.setup(width=1000, height=600)
turtle.mode("logo")
turtle.speed(0)
letterHeight = 58
largeSide = 29.0
smallerSide = 11.6
turtle.penup()
turtle.goto(-471.0,-29.0)
turtle.setheading(45)
turtle.forward( ( ( (2 * (letterHeight ** 2) ) ** (0.5) ) / 2) - ( (2 * ( (letterHeight / 4) ** 2) ) ** (0.5) ) )
turtle.pendown()
turtle.penup()
turtle.setheading(45)
turtle.forward(smallerSide)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(90)
turtle.forward(smallerSide)
turtle.setheading(210)
turtle.forward(smallerSide)
turtle.setheading(330)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.setheading(0)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(90)
turtle.forward(smallerSide)
turtle.setheading(330)
turtle.forward(smallerSide)
turtle.setheading(210)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(-355.0,-29.0)
turtle.setheading(45)
turtle.forward( ( ( (2 * (letterHeight ** 2) ) ** (0.5) ) / 2) - ( (2 * ( (letterHeight / 4) ** 2) ) ** (0.5) ) )
turtle.pendown()
turtle.penup()
turtle.setheading(90)
turtle.forward(smallerSide)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(330)
turtle.forward(largeSide / 2)
ReturnPoint = turtle.position()
turtle.forward(largeSide / 2)
turtle.setheading(90)
turtle.forward(largeSide)
turtle.setheading(210)
turtle.forward(largeSide / 4)
turtle.setheading(300)
turtle.circle(largeSide / 4, 180, int(largeSide / 4) )
turtle.setheading(210)
turtle.forward(largeSide / 4)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint)
turtle.setheading(270)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.forward(smallerSide)
turtle.setheading(30)
turtle.forward(smallerSide)
turtle.setheading(150)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.setheading(180)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(150)
turtle.forward(smallerSide)
turtle.setheading(270)
turtle.forward(smallerSide)
turtle.setheading(30)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(-297.0,-29.0)
turtle.setheading(45)
turtle.forward( ( ( (2 * (letterHeight ** 2) ) ** (0.5) ) / 2) - ( (2 * ( (letterHeight / 4) ** 2) ) ** (0.5) ) )
turtle.pendown()
turtle.penup()
turtle.setheading(90)
turtle.forward(smallerSide)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(0)
turtle.forward(largeSide / 2)
ReturnPoint = turtle.position()
turtle.forward(largeSide / 2)
turtle.setheading(120)
turtle.forward(largeSide)
turtle.setheading(240)
turtle.forward(largeSide / 4)
turtle.setheading(330)
turtle.circle(largeSide / 4, 180, int(largeSide / 4) )
turtle.setheading(240)
turtle.forward(largeSide / 4)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint)
turtle.setheading(270)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(0)
turtle.forward(smallerSide)
turtle.setheading(240)
turtle.forward(smallerSide)
turtle.setheading(120)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(-239.0,-29.0)
turtle.setheading(45)
turtle.forward( ( ( (2 * (letterHeight ** 2) ) ** (0.5) ) / 2) - ( (2 * ( (letterHeight / 4) ** 2) ) ** (0.5) ) )
turtle.pendown()
turtle.penup()
turtle.setheading(90)
turtle.forward(smallerSide)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(0)
turtle.forward(largeSide / 2)
ReturnPoint = turtle.position()
turtle.forward(largeSide / 2)
turtle.setheading(120)
turtle.forward(largeSide / 2)
ReturnPoint1 = turtle.position()
turtle.forward(largeSide / 2)
turtle.setheading(240)
turtle.forward(largeSide / 4)
turtle.setheading(330)
turtle.circle(largeSide / 4, 180, int(largeSide / 4) )
turtle.setheading(240)
turtle.forward(largeSide / 4)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint)
turtle.setheading(270)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(300)
turtle.forward(smallerSide)
turtle.setheading(60)
turtle.forward(smallerSide)
turtle.setheading(180)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint1)
turtle.setheading(30)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(0)
turtle.forward(smallerSide)
turtle.setheading(240)
turtle.forward(smallerSide)
turtle.setheading(120)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(-181.0,-29.0)
turtle.setheading(45)
turtle.forward( ( ( (2 * (letterHeight ** 2) ) ** (0.5) ) / 2) - ( (2 * ( (letterHeight / 4) ** 2) ) ** (0.5) ) )
turtle.pendown()
turtle.penup()
turtle.setheading(0)
turtle.forward(largeSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(60)
turtle.forward(largeSide / 2)
ReturnPoint = turtle.position()
turtle.forward(largeSide / 2)
ReturnPoint1 = turtle.position()
turtle.setheading(180)
turtle.forward(largeSide)
turtle.setheading(300)
turtle.forward(largeSide)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint)
turtle.setheading(0)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.forward(smallerSide)
turtle.setheading(120)
turtle.forward(smallerSide)
turtle.setheading(240)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint1)
turtle.setheading(90)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(120)
turtle.forward(smallerSide)
turtle.setheading(240)
turtle.forward(smallerSide)
turtle.setheading(0)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(-65.0,-29.0)
turtle.setheading(45)
turtle.forward( ( ( (2 * (letterHeight ** 2) ) ** (0.5) ) / 2) - ( (2 * ( (letterHeight / 4) ** 2) ) ** (0.5) ) )
turtle.pendown()
turtle.penup()
turtle.setheading(45)
turtle.forward(smallerSide)
turtle.setheading(0)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(60)
turtle.forward(largeSide / 2)
ReturnPoint = turtle.position()
turtle.forward(largeSide / 2)
turtle.setheading(180)
turtle.forward(largeSide / 4)
turtle.setheading(270)
turtle.circle(largeSide / 4, 180, int(largeSide / 4) )
turtle.setheading(180)
turtle.forward(largeSide / 4)
turtle.setheading(300)
turtle.forward(largeSide)
turtle.end_fill()

turtle.penup()
turtle.backward(largeSide / 2)
turtle.setheading(210)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(180)
turtle.forward(smallerSide)
turtle.setheading(60)
turtle.forward(smallerSide)
turtle.setheading(300)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint)
turtle.setheading(330)
turtle.forward(largeSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(180)
turtle.forward(smallerSide)
turtle.setheading(60)
turtle.forward(smallerSide)
turtle.setheading(300)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(-7.0,-29.0)
turtle.setheading(45)
turtle.forward( ( ( (2 * (letterHeight ** 2) ) ** (0.5) ) / 2) - ( (2 * ( (letterHeight / 4) ** 2) ) ** (0.5) ) )
turtle.pendown()
turtle.penup()
turtle.setheading(90)
turtle.forward(smallerSide)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(0)
turtle.forward(largeSide / 2)
ReturnPoint = turtle.position()
turtle.forward(largeSide / 2)
turtle.setheading(120)
turtle.forward(largeSide)
turtle.setheading(240)
turtle.forward(largeSide / 4)
turtle.setheading(330)
turtle.circle(largeSide / 4, 180, int(largeSide / 4) )
turtle.setheading(240)
turtle.forward(largeSide / 4)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint)
turtle.setheading(270)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(0)
turtle.forward(smallerSide)
turtle.setheading(240)
turtle.forward(smallerSide)
turtle.setheading(120)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(51.0,-29.0)
turtle.setheading(45)
turtle.forward( ( ( (2 * (letterHeight ** 2) ) ** (0.5) ) / 2) - ( (2 * ( (letterHeight / 4) ** 2) ) ** (0.5) ) )
turtle.pendown()
turtle.penup()
turtle.setheading(0)
turtle.forward(smallerSide)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(120)
turtle.forward(largeSide)
turtle.setheading(0)
turtle.forward(largeSide / 2)
ReturnPoint = turtle.position()
turtle.forward(largeSide / 2)
turtle.setheading(240)
turtle.forward(largeSide)
turtle.end_fill()

turtle.penup()
turtle.backward(largeSide / 2)
turtle.setheading(315)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(60)
turtle.forward(smallerSide)
turtle.setheading(300)
turtle.forward(smallerSide)
turtle.setheading(180)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint)
turtle.setheading(90)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(0)
turtle.forward(smallerSide)
turtle.setheading(120)
turtle.forward(smallerSide)
turtle.setheading(240)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(167.0,-29.0)
turtle.setheading(45)
turtle.forward( ( ( (2 * (letterHeight ** 2) ) ** (0.5) ) / 2) - ( (2 * ( (letterHeight / 4) ** 2) ) ** (0.5) ) )
turtle.pendown()
turtle.begin_fill()
turtle.setheading(30)
turtle.forward(largeSide / 2)
ReturnPoint = turtle.position()
turtle.forward(largeSide / 2)
turtle.setheading(150)
turtle.forward(largeSide / 2)
ReturnPoint1 = turtle.position()
turtle.forward(largeSide / 2)
turtle.setheading(270)
turtle.forward(largeSide / 4)
turtle.setheading(0)
turtle.circle(largeSide / 4, 180, int(largeSide / 4) )
turtle.setheading(270)
turtle.forward(largeSide / 4)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint)
turtle.setheading(300)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(270)
turtle.forward(smallerSide)
turtle.setheading(150)
turtle.forward(smallerSide)
turtle.setheading(30)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint1)
turtle.setheading(30)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(30)
turtle.forward(smallerSide)
turtle.setheading(270)
turtle.forward(smallerSide)
turtle.setheading(150)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(225.0,-29.0)
turtle.setheading(45)
turtle.forward( ( ( (2 * (letterHeight ** 2) ) ** (0.5) ) / 2) - ( (2 * ( (letterHeight / 4) ** 2) ) ** (0.5) ) )
turtle.pendown()
turtle.pendown()
turtle.begin_fill()
turtle.setheading(30)
turtle.forward(largeSide / 4)
turtle.setheading(120)
turtle.circle(largeSide / 4, 180, int(largeSide / 2) )
turtle.setheading(30)
turtle.forward(largeSide / 4)
turtle.setheading(150)
turtle.forward(largeSide / 2)
ReturnPoint = turtle.position()
turtle.forward(largeSide / 2)
turtle.setheading(270)
turtle.forward(largeSide)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint)
turtle.setheading(90)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.forward(smallerSide)
turtle.setheading(210)
turtle.forward(smallerSide)
turtle.setheading(330)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(283.0,-29.0)
turtle.setheading(45)
turtle.forward( ( ( (2 * (letterHeight ** 2) ) ** (0.5) ) / 2) - ( (2 * ( (letterHeight / 4) ** 2) ) ** (0.5) ) )
turtle.pendown()
turtle.penup()
turtle.setheading(45)
turtle.forward(smallerSide)
turtle.setheading(0)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(60)
turtle.forward(largeSide / 2)
ReturnPoint = turtle.position()
turtle.forward(largeSide / 2)
turtle.setheading(180)
turtle.forward(largeSide / 4)
turtle.setheading(270)
turtle.circle(largeSide / 4, 180, int(largeSide / 4) )
turtle.setheading(180)
turtle.forward(largeSide / 4)
turtle.setheading(300)
turtle.forward(largeSide)
turtle.end_fill()

turtle.penup()
turtle.backward(largeSide / 2)
turtle.setheading(210)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(180)
turtle.forward(smallerSide)
turtle.setheading(60)
turtle.forward(smallerSide)
turtle.setheading(300)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint)
turtle.setheading(330)
turtle.forward(largeSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(180)
turtle.forward(smallerSide)
turtle.setheading(60)
turtle.forward(smallerSide)
turtle.setheading(300)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(341.0,-29.0)
turtle.setheading(45)
turtle.forward( ( ( (2 * (letterHeight ** 2) ) ** (0.5) ) / 2) - ( (2 * ( (letterHeight / 4) ** 2) ) ** (0.5) ) )
turtle.pendown()
turtle.pendown()
turtle.begin_fill()
turtle.setheading(0)
turtle.forward(largeSide / 4)
turtle.setheading(90)
turtle.circle(largeSide / 4, 180, int(largeSide / 4) )
turtle.setheading(0)
turtle.forward(largeSide / 4)
turtle.setheading(120)
turtle.forward(largeSide / 2)
ReturnPoint = turtle.position()
turtle.forward(largeSide / 2)
turtle.setheading(240)
turtle.forward(largeSide / 2)
ReturnPoint1 = turtle.position()
turtle.forward(largeSide / 2)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint)
turtle.setheading(45)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(60)
turtle.forward(smallerSide)
turtle.setheading(180)
turtle.forward(smallerSide)
turtle.setheading(300)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint1)
turtle.setheading(135)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(60)
turtle.forward(smallerSide)
turtle.setheading(180)
turtle.forward(smallerSide)
turtle.setheading(300)
turtle.forward(smallerSide)
turtle.end_fill()


turtle.penup()
turtle.goto(399.0,-29.0)
turtle.setheading(45)
turtle.forward( ( ( (2 * (letterHeight ** 2) ) ** (0.5) ) / 2) - ( (2 * ( (letterHeight / 4) ** 2) ) ** (0.5) ) )
turtle.pendown()
turtle.penup()
turtle.setheading(0)
turtle.forward(largeSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(60)
turtle.forward(largeSide / 2)
ReturnPoint = turtle.position()
turtle.forward(largeSide / 2)
ReturnPoint1 = turtle.position()
turtle.setheading(180)
turtle.forward(largeSide)
turtle.setheading(300)
turtle.forward(largeSide)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint)
turtle.setheading(0)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.forward(smallerSide)
turtle.setheading(120)
turtle.forward(smallerSide)
turtle.setheading(240)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint1)
turtle.setheading(90)
turtle.forward(smallerSide / 2)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(120)
turtle.forward(smallerSide)
turtle.setheading(240)
turtle.forward(smallerSide)
turtle.setheading(0)
turtle.forward(smallerSide)
turtle.end_fill()

turtle.done()
