import turtle
window = turtle.Screen()
window.setup(width=1000, height=600)
turtle.mode("logo")
turtle.speed(0)
direction = 0

up = 0
if direction == 3:
    up = 270
if direction == 4:
    up = 90
right = 90
if direction == 2:
    right = 270
if direction == 3:
    right = 0
if direction == 4:
    right = 180
down = 180
if direction == 3:
    down = 90
if direction == 4:
    down = 270
left = 270
if direction == 2:
    left = 90
if direction == 3:
    left = 180
if direction == 4:
    left = 0

turtle.penup()
turtle.goto(-471.0,-29.0)
turtle.pendown()
length = 8.285714285714286
bottomLeft = (-471.0, -29.0)
bottomRight = (-413.0, -29.0)
topLeft = (-471.0, 29.0)
topRight = (-413.0, 29.0)
turtle.penup()
turtle.goto(bottomLeft)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(up)
turtle.forward(length * 7)
turtle.setheading(right)
turtle.forward(length * 3)
turtle.setheading(down)
turtle.forward(length * 6)
turtle.setheading(right)
turtle.forward(length * 2)
turtle.setheading(down)
turtle.forward(length)
ReturnPoint = turtle.position()
turtle.setheading(left)
turtle.forward(length * 3)
turtle.setheading(up)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint)
turtle.setheading(up)
turtle.forward(length * 6)
turtle.pendown()
turtle.begin_fill()
turtle.forward(length)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length)
turtle.setheading(right)
turtle.forward(length)
turtle.end_fill()

turtle.penup()
turtle.goto(-355.0,-29.0)
turtle.pendown()
length = 8.285714285714286
bottomLeft = (-355.0, -29.0)
bottomRight = (-297.0, -29.0)
topLeft = (-355.0, 29.0)
topRight = (-297.0, 29.0)
turtle.penup()
turtle.goto(bottomLeft)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(up)
turtle.forward(length)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length * 6)
turtle.setheading(right)
turtle.forward(length * 4)
turtle.setheading(down)
turtle.forward(length * 6)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length)
ReturnPoint = turtle.position()
turtle.setheading(left)
turtle.forward(length * 3)
turtle.setheading(up)
turtle.forward(length * 3)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length * 2)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length * 2)
turtle.end_fill()

turtle.penup()
turtle.setheading(right)
turtle.forward(length * 2)
turtle.pendown()
turtle.begin_fill()
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length)
turtle.end_fill()

turtle.penup()
turtle.goto(-297.0,-29.0)
turtle.pendown()
length = 8.285714285714286
bottomLeft = (-297.0, -29.0)
bottomRight = (-239.0, -29.0)
topLeft = (-297.0, 29.0)
topRight = (-239.0, 29.0)
turtle.penup()
turtle.goto(bottomLeft)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(up)
turtle.forward(length * 7)
turtle.setheading(right)
turtle.forward(length * 3)
turtle.setheading(down)
turtle.forward(length * 7)
ReturnPoint = turtle.position()
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length)
turtle.end_fill()

turtle.penup()
turtle.goto(-239.0,-29.0)
turtle.pendown()
length = 8.285714285714286
bottomLeft = (-239.0, -29.0)
bottomRight = (-181.0, -29.0)
topLeft = (-239.0, 29.0)
topRight = (-181.0, 29.0)
turtle.penup()
turtle.goto(bottomLeft)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(up)
turtle.forward(length)
turtle.setheading(right)
turtle.forward(length * 2)
turtle.setheading(up)
turtle.forward(length * 5)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length * 3)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length * 4)
turtle.setheading(right)
turtle.forward(length * 5)
turtle.setheading(down)
turtle.forward(length * 6)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length)
ReturnPoint = turtle.position()
turtle.setheading(left)
turtle.forward(length * 2)
turtle.setheading(up)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length * 3)
turtle.end_fill()

turtle.penup()
turtle.goto(-181.0,-29.0)
turtle.pendown()
length = 8.285714285714286
bottomLeft = (-181.0, -29.0)
bottomRight = (-123.0, -29.0)
topLeft = (-181.0, 29.0)
topRight = (-123.0, 29.0)
turtle.penup()
turtle.goto(topLeft)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(right)
turtle.forward(length * 3)
turtle.setheading(down)
turtle.forward(length * 7)
ReturnPoint = turtle.position()
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length * 2)
turtle.setheading(up)
turtle.forward(length)
turtle.end_fill()

turtle.setheading(down)
turtle.forward(length)
turtle.begin_fill()
turtle.forward(length * 6)
turtle.setheading(right)
turtle.forward(length * 2)
turtle.setheading(up)
turtle.forward(length)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length * 5)
turtle.setheading(left)
turtle.forward(length)
turtle.end_fill()

turtle.penup()
turtle.goto(-65.0,-29.0)
turtle.pendown()
length = 8.285714285714286
bottomLeft = (-65.0, -29.0)
bottomRight = (-7.0, -29.0)
topLeft = (-65.0, 29.0)
topRight = (-7.0, 29.0)
turtle.penup()
turtle.goto(bottomLeft)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(up)
turtle.forward(length)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length * 3)
turtle.setheading(right)
turtle.forward(length * 4)
turtle.setheading(down)
turtle.forward(length * 6)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length)
ReturnPoint = turtle.position()
turtle.setheading(left)
turtle.forward(length * 2)
turtle.setheading(up)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length * 2)
turtle.end_fill()

turtle.penup()
turtle.goto(-7.0,-29.0)
turtle.pendown()
length = 8.285714285714286
bottomLeft = (-7.0, -29.0)
bottomRight = (51.0, -29.0)
topLeft = (-7.0, 29.0)
topRight = (51.0, 29.0)
turtle.penup()
turtle.goto(bottomLeft)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(up)
turtle.forward(length * 7)
turtle.setheading(right)
turtle.forward(length * 3)
turtle.setheading(down)
turtle.forward(length * 7)
ReturnPoint = turtle.position()
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length)
turtle.end_fill()

turtle.penup()
turtle.goto(51.0,-29.0)
turtle.pendown()
length = 8.285714285714286
bottomLeft = (51.0, -29.0)
bottomRight = (109.0, -29.0)
topLeft = (51.0, 29.0)
topRight = (109.0, 29.0)
turtle.penup()
turtle.goto(bottomLeft)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(up)
turtle.forward(length * 7)
turtle.setheading(right)
turtle.forward(length * 3)
ReturnPoint = turtle.position()
turtle.setheading(down)
turtle.forward(length * 7)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length)
turtle.end_fill()

turtle.penup()
turtle.goto(ReturnPoint)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length * 2)
turtle.pendown()
turtle.begin_fill()
turtle.forward(length * 3)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length * 3)
turtle.setheading(left)
turtle.forward(length)
turtle.end_fill()

turtle.penup()
turtle.goto(167.0,-29.0)
turtle.pendown()
length = 8.285714285714286
bottomLeft = (167.0, -29.0)
bottomRight = (225.0, -29.0)
topLeft = (167.0, 29.0)
topRight = (225.0, 29.0)
turtle.penup()
turtle.goto(bottomLeft)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(up)
turtle.forward(length)
turtle.setheading(right)
turtle.forward(length * 2)
turtle.setheading(down)
turtle.forward(length)
turtle.setheading(left)
turtle.forward(length * 2)
turtle.end_fill()

turtle.penup()
turtle.setheading(up)
turtle.forward(length * 2)
turtle.pendown()
turtle.begin_fill()
turtle.forward(length * 3)
turtle.setheading(right)
turtle.forward(length * 2)
turtle.setheading(down)
turtle.forward(length)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length)
turtle.setheading(left)
turtle.forward(length * 2)
turtle.end_fill()

turtle.penup()
turtle.goto(topLeft)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(right)
turtle.forward(length * 4)
turtle.setheading(down)
turtle.forward(length * 6)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length)
ReturnPoint = turtle.position()
turtle.setheading(left)
turtle.forward(length * 2)
turtle.setheading(up)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length * 3)
turtle.setheading(up)
turtle.forward(length)
turtle.end_fill()

turtle.penup()
turtle.goto(225.0,-29.0)
turtle.pendown()
length = 8.285714285714286
bottomLeft = (225.0, -29.0)
bottomRight = (283.0, -29.0)
topLeft = (225.0, 29.0)
topRight = (283.0, 29.0)
turtle.penup()
turtle.goto(bottomLeft)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(up)
turtle.forward(length * 7)
turtle.setheading(right)
turtle.forward(length * 3)
turtle.setheading(down)
turtle.forward(length * 3)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length)
ReturnPoint = turtle.position()
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length * 3)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length)
turtle.end_fill()

turtle.penup()
turtle.goto(283.0,-29.0)
turtle.pendown()
length = 8.285714285714286
bottomLeft = (283.0, -29.0)
bottomRight = (341.0, -29.0)
topLeft = (283.0, 29.0)
topRight = (341.0, 29.0)
turtle.penup()
turtle.goto(bottomLeft)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(up)
turtle.forward(length)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length * 3)
turtle.setheading(right)
turtle.forward(length * 4)
turtle.setheading(down)
turtle.forward(length * 6)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length)
ReturnPoint = turtle.position()
turtle.setheading(left)
turtle.forward(length * 2)
turtle.setheading(up)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length * 2)
turtle.end_fill()

turtle.penup()
turtle.goto(341.0,-29.0)
turtle.pendown()
length = 8.285714285714286
bottomLeft = (341.0, -29.0)
bottomRight = (399.0, -29.0)
topLeft = (341.0, 29.0)
topRight = (399.0, 29.0)
turtle.penup()
turtle.goto(topLeft)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(right)
turtle.forward(length * 4)
turtle.setheading(down)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length * 5)
turtle.setheading(left)
turtle.forward(length * 3)
turtle.setheading(up)
turtle.forward(length)
turtle.end_fill()

turtle.penup()
turtle.goto(bottomLeft)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(up)
turtle.forward(length * 3)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length * 2)
turtle.setheading(right)
turtle.forward(length)
turtle.setheading(down)
turtle.forward(length)
turtle.setheading(right)
turtle.forward(length * 2)
turtle.setheading(down)
turtle.forward(length * 3)
turtle.setheading(left)
turtle.forward(length * 2)
turtle.setheading(down)
turtle.forward(length)
turtle.setheading(right)
turtle.forward(length * 4)
turtle.setheading(down)
turtle.forward(length)
ReturnPoint = turtle.position()
turtle.setheading(left)
turtle.forward(length * 5)
turtle.end_fill()

turtle.penup()
turtle.goto(399.0,-29.0)
turtle.pendown()
length = 8.285714285714286
bottomLeft = (399.0, -29.0)
bottomRight = (457.0, -29.0)
topLeft = (399.0, 29.0)
topRight = (457.0, 29.0)
turtle.penup()
turtle.goto(topLeft)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(right)
turtle.forward(length * 3)
turtle.setheading(down)
turtle.forward(length * 7)
ReturnPoint = turtle.position()
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length * 6)
turtle.setheading(left)
turtle.forward(length * 2)
turtle.setheading(up)
turtle.forward(length)
turtle.end_fill()

turtle.setheading(down)
turtle.forward(length)
turtle.begin_fill()
turtle.forward(length * 6)
turtle.setheading(right)
turtle.forward(length * 2)
turtle.setheading(up)
turtle.forward(length)
turtle.setheading(left)
turtle.forward(length)
turtle.setheading(up)
turtle.forward(length * 5)
turtle.setheading(left)
turtle.forward(length)
turtle.end_fill()

turtle.done()
