import turtle
window = turtle.Screen()
window.setup(width = 600, height=600)

letterHeight = 400
lineWidth = 20
rightWall = 0
returnPoint = 0,0

turtle.mode("logo")
turtle.penup()
turtle.pencolor("red")
turtle.goto(-300, -250)
turtle.pendown()
turtle.setheading(90)
turtle.forward(600)
turtle.penup()
turtle.goto(250, -300)
turtle.pendown()
turtle.setheading(0)
turtle.forward(600)
turtle.penup()
turtle.goto(300, 250)
turtle.pendown()
turtle.setheading(270)
turtle.forward(600)
turtle.penup()
turtle.goto(-250, 300)
turtle.pendown()
turtle.setheading(180)
turtle.forward(600)
turtle.penup()
turtle.pencolor("blacK")

turtle.goto(-lineWidth / 2, -lineWidth / 2)
turtle.pendown()


#START
turtle.pendown()
turtle.begin_fill()
turtle.setheading(135)
returnPoint = turtle.position()
turtle.circle(lineWidth, 180)
returnPoint1 = turtle.position()
turtle.setheading(315)
turtle.forward(lineWidth * 2)
returnPoint2 = turtle.position()
turtle.setheading(315)
turtle.circle(lineWidth, -180)
turtle.setheading(135)
turtle.forward(lineWidth * 2)
turtle.end_fill()

turtle.circle(lineWidth, 60)
turtle.begin_fill()
turtle.setheading(135)
turtle.forward(letterHeight / 2)
turtle.circle(lineWidth / 2, 180)
rightWall = turtle.xcor()
turtle.forward(letterHeight / 2)
turtle.end_fill()

turtle.penup()
turtle.goto(returnPoint2)
turtle.pendown()
turtle.setheading(315)
turtle.circle(lineWidth, 180)

turtle.setheading(240)
turtle.forward(letterHeight / 3)
turtle.circle(lineWidth, 180)
turtle.goto(returnPoint)

turtle.setheading(240)
turtle.forward(letterHeight / 6)
turtle.circle(lineWidth, 180)
turtle.goto(returnPoint)

turtle.penup()
turtle.goto(returnPoint2)
turtle.pendown()
turtle.setheading(30)
turtle.forward(letterHeight / 3)
turtle.circle(-lineWidth, 180)
turtle.goto(returnPoint1)

turtle.setheading(30)
turtle.forward(letterHeight / 6)
turtle.circle(-lineWidth, 180)
turtle.goto(returnPoint1)
#END

turtle.penup()
turtle.goto(rightWall, -300)
turtle.pencolor("blue")
turtle.pendown()
turtle.setheading(0)
turtle.forward(600)
turtle.done()