import turtle
window = turtle.Screen()
window.setup(width = 600, height=600)

letterHeight = 400
lineWidth = 20
rightWall = 0
returnPoint = 0,0

turtle.mode("logo")
turtle.penup()
turtle.pencolor("red")
turtle.goto(-300, -250)
turtle.pendown()
turtle.setheading(90)
turtle.forward(600)
turtle.penup()
turtle.goto(250, -300)
turtle.pendown()
turtle.setheading(0)
turtle.forward(600)
turtle.penup()
turtle.goto(300, 250)
turtle.pendown()
turtle.setheading(270)
turtle.forward(600)
turtle.penup()
turtle.goto(-250, 300)
turtle.pendown()
turtle.setheading(180)
turtle.forward(600)
turtle.penup()
turtle.pencolor("blacK")

turtle.goto(0, -letterHeight / 2 + lineWidth)
turtle.pendown()


#START
headingReturn = 0
legDrawingReturnPosition = 0
bodyDrawingPenSize = 0

returnPoint = turtle.position()
turtle.setheading(90)
turtle.circle(letterHeight / 4, 30)
legDrawingReturnPosition = turtle.position()
headingReturn = turtle.heading()
turtle.setheading(90)
bodyDrawingPenSize = turtle.pensize()
turtle.pensize(bodyDrawingPenSize + 2)
turtle.circle(-letterHeight / 8, 90)
turtle.pensize(bodyDrawingPenSize)
turtle.penup()
turtle.goto(legDrawingReturnPosition)
turtle.pendown()
turtle.setheading(headingReturn)

turtle.circle(letterHeight / 2, 60)
legDrawingReturnPosition = turtle.position()
headingReturn = turtle.heading()
turtle.setheading(90)
bodyDrawingPenSize = turtle.pensize()
turtle.pensize(bodyDrawingPenSize + 2)
turtle.circle(-letterHeight / 8, 90)
rightWall = turtle.xcor()
turtle.pensize(bodyDrawingPenSize)
turtle.penup()
turtle.goto(legDrawingReturnPosition)
turtle.pendown()
turtle.setheading(headingReturn)

turtle.circle(letterHeight / 2, 30)
legDrawingReturnPosition = turtle.position()
headingReturn = turtle.heading()
turtle.setheading(30)
bodyDrawingPenSize = turtle.pensize()
turtle.pensize(bodyDrawingPenSize + 2)
turtle.circle(-letterHeight / 8, 90)
turtle.pensize(bodyDrawingPenSize)
turtle.penup()
turtle.goto(legDrawingReturnPosition)
turtle.pendown()
turtle.setheading(headingReturn)

returnPoint1 = turtle.position()
turtle.begin_fill()
turtle.circle(letterHeight / 2, 30)
turtle.circle(letterHeight / 4, 30)
returnPoint2 = turtle.position()
turtle.circle(letterHeight / 4, 30)
turtle.circle(letterHeight / 2, 30)
returnPoint3 = turtle.position()
turtle.setheading(0)
turtle.circle( (-1 / 2) * (returnPoint1[0] - turtle.xcor() ), 180)
turtle.end_fill()

turtle.penup()
turtle.goto(returnPoint)
turtle.pendown()
turtle.setheading(0)
turtle.forward( (returnPoint2[1] - returnPoint[1]) / 2)

turtle.penup()
turtle.setheading(90)
turtle.forward(lineWidth * 1.5)
turtle.setheading(135)
turtle.pendown()
turtle.begin_fill()
turtle.circle(lineWidth)
turtle.end_fill()

turtle.penup()
turtle.setheading(270)
turtle.forward(lineWidth * 3)
turtle.setheading(315)
turtle.pendown()
turtle.begin_fill()
turtle.circle(lineWidth)
turtle.end_fill()

turtle.penup()
turtle.setheading(90)
turtle.forward(lineWidth * 1.5)
turtle.pendown()
turtle.goto(returnPoint2)

turtle.setheading(270)
turtle.circle(letterHeight / 4, 30)
turtle.circle(letterHeight / 2, 30)
legDrawingReturnPosition = turtle.position()
headingReturn = turtle.heading()
turtle.setheading(120)
bodyDrawingPenSize = turtle.pensize()
turtle.pensize(bodyDrawingPenSize + 2)
turtle.circle(-letterHeight / 8, -90)
turtle.pensize(bodyDrawingPenSize)
turtle.penup()
turtle.goto(legDrawingReturnPosition)
turtle.pendown()
turtle.setheading(headingReturn)

turtle.circle(letterHeight / 2, 30)
legDrawingReturnPosition = turtle.position()
headingReturn = turtle.heading()
turtle.setheading(90)
bodyDrawingPenSize = turtle.pensize()
turtle.pensize(bodyDrawingPenSize + 2)
turtle.circle(-letterHeight / 8, -90)
turtle.pensize(bodyDrawingPenSize)
turtle.penup()
turtle.goto(legDrawingReturnPosition)
turtle.pendown()
turtle.setheading(headingReturn)

turtle.circle(letterHeight / 2, 60)
legDrawingReturnPosition = turtle.position()
headingReturn = turtle.heading()
turtle.setheading(60)
bodyDrawingPenSize = turtle.pensize()
turtle.pensize(bodyDrawingPenSize + 2)
turtle.circle(-letterHeight / 8, -90)
turtle.pensize(bodyDrawingPenSize)
turtle.penup()
turtle.goto(legDrawingReturnPosition)
turtle.pendown()
turtle.setheading(headingReturn)

turtle.circle(letterHeight / 4, 30)
#END

turtle.penup()
turtle.goto(rightWall, -300)
turtle.pencolor("blue")
turtle.pendown()
turtle.setheading(0)
turtle.forward(600)
turtle.done()