import turtle
window = turtle.Screen()
window.setup(width = 600, height=600)

letterHeight = 400
lineWidth = 20
rightWall = 0
returnPoint = 0,0

turtle.mode("logo")
turtle.penup()
turtle.pencolor("red")
turtle.goto(-300, -250)
turtle.pendown()
turtle.setheading(90)
turtle.forward(600)
turtle.penup()
turtle.goto(250, -300)
turtle.pendown()
turtle.setheading(0)
turtle.forward(600)
turtle.penup()
turtle.goto(300, 250)
turtle.pendown()
turtle.setheading(270)
turtle.forward(600)
turtle.penup()
turtle.goto(-250, 300)
turtle.pendown()
turtle.setheading(180)
turtle.forward(600)
turtle.penup()
turtle.pencolor("blacK")

turtle.goto(-lineWidth / 2, -letterHeight / 2)
turtle.pendown()


#START
startPoint = turtle.position()
turtle.setheading(90)
turtle.circle(letterHeight / 4, 60)
turtle.setheading(0)
turtle.circle(-letterHeight / 16, 180)
turtle.setheading(0)
turtle.circle(letterHeight / 8, 75)
turtle.setheading(0)
turtle.circle(-letterHeight / 16, 180)
turtle.setheading(0)
turtle.circle(letterHeight / 8, 75)
turtle.setheading(0)
turtle.circle(-letterHeight / 16, 180)
rightWall = turtle.xcor()
turtle.setheading(0)
turtle.circle(letterHeight / 8, 90)
returnPoint = turtle.position()

turtle.penup()
turtle.goto(startPoint)
turtle.pendown()
turtle.setheading(270)
turtle.circle(-letterHeight / 4, 60)
turtle.setheading(0)
turtle.circle(letterHeight / 16, 180)
turtle.setheading(0)
turtle.circle(-letterHeight / 8, 75)
turtle.setheading(0)
turtle.circle(letterHeight / 16, 180)
turtle.setheading(0)
turtle.circle(-letterHeight / 8, 75)
turtle.setheading(0)
turtle.circle(letterHeight / 16, 180)
turtle.setheading(0)
turtle.circle(-letterHeight / 8, 90)

gapDistance = returnPoint[0] - turtle.xcor()
returnPoint = turtle.position()
turtle.setheading(60)
turtle.circle(-gapDistance, 60)

turtle.setheading(90)
turtle.circle(letterHeight / 8, 180)
turtle.setheading(180)
turtle.forward(letterHeight / 4)

turtle.penup()
turtle.goto(returnPoint)
turtle.pendown()
turtle.setheading(270)
turtle.circle(-letterHeight / 8, 180)
turtle.setheading(180)
turtle.forward(letterHeight / 4)
#END

turtle.penup()
turtle.goto(rightWall, -300)
turtle.pencolor("blue")
turtle.pendown()
turtle.setheading(0)
turtle.forward(600)
turtle.done()